server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/parking
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
co:
  anilozturk:
    language: tr
    region: TR


