INSERT INTO PARKING_SPOT (id, size, state) VALUES (1, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (2, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (3, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (4, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (5, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (6, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (7, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (8, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (9, 1, false);
INSERT INTO PARKING_SPOT (id, size, state) VALUES (10,1, false);